import type { Metadata } from "next";
import "./globals.css";
import { AppProviders } from '@/components/app-providers';
import { AppLayout } from "@/components/app-layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links: { label: string; path: string }[] = [
  // More links...
  { label: 'About Us', path: '/about' },
  { label: 'Support', path: '/support' },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <AppProviders>
          <AppLayout children={children} links={links} />
        </AppProviders>
      </body>
    </html>
  );
}
